name: Publish release

on:
  release:
    types: [created]

jobs:
  publish-pypi:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout latest code
      uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Setup KIND (kubernetes in docker)
      uses: engineerd/setup-kind@v0.5.0
      with:
        version: "v0.9.0"
    - name: Install dependencies
      run: |
        make init
    - name: Test
      run: |
        make test
    - name: bulid package
      run: |
        make dist
    - name: Publish a Python distribution to PyPI
      uses: pypa/gh-action-pypi-publish@master
      with:
        user: __token__
        password: ${{ secrets.pypi_password }}
  publish-docker:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout latest code
      uses: actions/checkout@v2
    - name: Get the version
      id: get_version
      run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
      # access it through ${{ steps.get_version.outputs.VERSION }}
    - name: Build and Push
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: staroid/${{ github.event.repository.name }}
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        tags: "${{ steps.get_version.outputs.VERSION }}"